export const Routes = {
    // pages
    Signin: { path: "/" },
    DashboardOverview: { path: "/dashboard" },
    Designations: { path: "/designations" },
    Title: { path: "/title" },
    District: { path: "/district" },
    State: { path: "/state" },
    Role: { path: "/role" },
    DDOType: { path: "/ddoType" },
    RTIDesignations: { path: "/rti-designations" },
    Module: { path: "/module" },
    Office: { path: "/officeDetails" },
    OfficeUnit: { path: "/officeUnit" },
    Profile: { path: "/profile" },
    Settings: { path: "/settings" },
    BootstrapTables: { path: "/tables/bootstrap-tables" },
    Signup: { path: "/auth/sign-up" },
    ForgotPassword: { path: "/auth/forgot-password" },
    ResetPassword: { path: "/auth/reset-password" },
    Lock: { path: "/auth/lock" },
    NotFound: { path: "/examples/404" },
    ServerError: { path: "/examples/500" },
    // components
    Accordions: { path: "/components/accordions" },
    Alerts: { path: "/components/alerts" },
    Badges: { path: "/components/badges" },
    Widgets: { path: "/widgets" },
    Breadcrumbs: { path: "/components/breadcrumbs" },
    Buttons: { path: "/components/buttons" },
    Forms: { path: "/components/forms" },
    Modals: { path: "/components/modals" },
    Navs: { path: "/components/navs" },
    Navbars: { path: "/components/navbars" },
    Pagination: { path: "/components/pagination" },
    Popovers: { path: "/components/popovers" },
    Progress: { path: "/components/progress" },
    Tables: { path: "/components/tables" },
    Tabs: { path: "/components/tabs" },
    Tooltips: { path: "/components/tooltips" },
    Toasts: { path: "/components/toasts" },
    WidgetsComponent: { path: "/components/widgets" }
};
export default Routes;